RPDSS/Controllers/FuzzySuitabilityIntervalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RPDSS.DataLayer.Repositories;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class FuzzySuitabilityIntervalController : Controller
    {
        private FuzzySuitabilityIntervalRepository _model;

        public FuzzySuitabilityIntervalController(IConfiguration config)
        {
            _model = new FuzzySuitabilityIntervalRepository(config);
        }

        public IActionResult Index()
        {
            return View(_model.GetAll());
        }

        public IActionResult New()
        {
            var item = new FuzzySuitabilityIntervalModel();
            return View("Form", item);
        }

        public IActionResult Edit(int id)
        {
            return View("Form", _model.GetById(id));
        }

        public IActionResult Details(int id, bool isfordetails)
        {
            var item = _model.GetById(id);
            return View(isfordetails ? "Details" : "Delete", item);
        }

        public IActionResult Delete(int id)
        {
            _model.Delete(id);
            return View("Index", _model.GetAll());
        }

        public IActionResult Save(FuzzySuitabilityIntervalModel item)
        {
            if (item.Id == 0)
                _model.New(item);
            else
                _model.Update(item);
            return View("Index", _model.GetAll());
        }
    }
}

RPDSS/Views/FuzzySuitabilityInterval/Delete.cshtml
@model RPDSS.DataLayer.Models.FuzzySuitabilityIntervalModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FuzzySuitabilityInterval</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Min)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Min)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Max)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Max)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.ActionLink("Delete", "Delete", new { Model.Id }) |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RPDSS/Views/FuzzySuitabilityInterval/Details.cshtml
@model RPDSS.DataLayer.Models.FuzzySuitabilityIntervalModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>FuzzySuitabilityInterval Details</h2>
<hr />

<div>    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Min)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Min)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Max)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Max)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

RPDSS/Views/FuzzySuitabilityInterval/Form.cshtml
@model RPDSS.DataLayer.Models.FuzzySuitabilityIntervalModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>Fuzzy Suitability Interval Data</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Save", "FuzzySuitabilityInterval"))
            {
            @Html.HiddenFor(m => m.Id)

            <div class="form-group">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Min)
                @Html.TextBoxFor(m => m.Min, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Max)
                @Html.TextBoxFor(m => m.Max, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
            </div>

            <div class="btn-group">
                <button type="submit" class="btn btn-primary" style="width:80px">Save</button>
                <a asp-action="Index" class="btn btn-info" style="width:80px">Back</a>
            </div>
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPDSS/Views/FuzzySuitabilityInterval/Index.cshtml
@model IEnumerable<RPDSS.DataLayer.Models.FuzzySuitabilityIntervalModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>Fuzzy Suitability Interval</h2>

<p>
    <a asp-action="New">Create New</a>
</p>
<table class="table table-striped table-hover table-sm">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Min)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Max)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Min)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Max)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id, isfordetails = true }) |
                @Html.ActionLink("Delete", "Details", new { id = item.Id, isfordetails = false })
            </td>
        </tr>
}
    </tbody>
</table>