RPDSS/Controllers/FrontEndController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class FrontEndController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RPDSS/Controllers/RainfallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RPDSS.DataLayer.Repositories;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class RainfallController : Controller
    {
        private RainfallRepository _model;

        public RainfallController(IConfiguration config)
        {
            _model = new RainfallRepository(config);
        }

        public IActionResult Index()
        {
            return View(_model.GetAll());
        }

        public IActionResult New()
        {
            var item = new RainfallDataEntryModel();
            item.Calendar = _model.GetLookup();
            return View("Form", item);
        }

        public IActionResult Edit(int id)
        {
            var item = new RainfallDataEntryModel
            {
                Rainfall = _model.GetById(id),
                Calendar = _model.GetLookup()
            };
            return View("Form", item);
        }

        public IActionResult Details(int id, bool isfordetails)
        {
            var item = _model.GetById(id);
            return View(isfordetails ? "Details" : "Delete", item);
        }

        public IActionResult Delete(int id)
        {
            _model.Delete(id);
            return View("Index", _model.GetAll());
        }

        public IActionResult Save(RainfallDataEntryModel item)
        {
            if (item.Rainfall.Id == 0)
                _model.New(item.Rainfall);
            else
                _model.Update(item.Rainfall);
            return View("Index", _model.GetAll());
        }
    }
}

RPDSS/Controllers/RiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RPDSS.DataLayer.Repositories;
using Microsoft.Extensions.Configuration;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class RiceController : Controller
    {
        private RiceRepository _model;

        public RiceController(IConfiguration config)
        {
            _model = new RiceRepository(config);
        }

        public IActionResult Index()
        {
            return View(_model.GetAll());
        }

        public IActionResult New()
        {
            var item = new RiceModel();
            return View("Form", item);
        }

        public IActionResult Edit(int id)
        {
            var item = _model.GetById(id);
            return View("Form", item);
        }

        public IActionResult Details(int id, bool isfordetails)
        {
            var item = _model.GetById(id);
            return View(isfordetails ? "Details" : "Delete", item);
        }

        public IActionResult Delete(int id)
        {
            _model.Delete(id);
            return View("Index", _model.GetAll());
        }

        public IActionResult Save(RiceModel item)
        {
            if (item.Id == 0)
                _model.New(item);
            else
                _model.Update(item);
            return View("Index", _model.GetAll());
        }
    }
}

RPDSS/Controllers/TemperatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RPDSS.DataLayer.Repositories;
using Microsoft.Extensions.Configuration;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class TemperatureController : Controller
    {
        private TemperatureRepository _model;

        public TemperatureController(IConfiguration config)
        {
            _model = new TemperatureRepository(config);
        }

        public IActionResult Index()
        {
            return View(_model.GetAll());
        }

        public IActionResult New()
        {
            var item = new TemperatureDataEntryModel();
            item.Calendar = _model.GetLookup();
            return View("Form", item);
        }

        public IActionResult Edit(int id)
        {
            var item = new TemperatureDataEntryModel
            {
                Temperature = _model.GetById(id),
                Calendar = _model.GetLookup()
            };
            return View("Form", item);
        }

        public IActionResult Details(int id, bool isfordetails)
        {
            var item = _model.GetById(id);
            return View(isfordetails ? "Details" : "Delete", item);
        }

        public IActionResult Delete(int id)
        {
            _model.Delete(id);
            return View("Index", _model.GetAll());
        }

        public IActionResult Save(TemperatureDataEntryModel item)
        {
            if (item.Temperature.Id == 0)
                _model.New(item.Temperature);
            else
                _model.Update(item.Temperature);
            return View("Index", _model.GetAll());
        }
    }
}

RPDSS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RPDSS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.superhero.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.superhero.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RPDSS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Growth Duration</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Planting Season</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Crop Calendar</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Login">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - RPDSS</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/chart.js/dist/Chart.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

RPDSS/Views/Shared/_LayoutBackend.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Admin Panel</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.superhero.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.superhero.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RPDSS Admin Panel</a>
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Rainfall" asp-action="Index">Rainfall</a></li>
                    <li><a asp-area="" asp-controller="Temperature" asp-action="Index">Temperature</a></li>
                    <li><a asp-area="" asp-controller="Rice" asp-action="Index">Rice</a></li>
                    <li><a asp-area="" asp-controller="FuzzyParameter" asp-action="Index">Fuzzy Parameters</a></li>
                    <li><a asp-area="" asp-controller="FuzzySuitabilityInterval" asp-action="Index">Fuzzy Suitability Interval</a></li>
                </ul>
            </div>*@
        </div>
    </nav>
    <div class="container body-content">
        <div class="row">
            <div class="col-sm-3">
                <br />
                <ul class="list-group">
                    <li class="list-group-item">
                        <h4><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span> Admin Menu</h4>
                        <hr/>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="Rice" asp-action="Index"><span class="glyphicon glyphicon-leaf" aria-hidden="true"></span> Rice Profiles</a></h5>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="Rainfall" asp-action="Index"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Rainfall Data</a></h5>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="Temperature" asp-action="Index"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Temperature Data</a></h5>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="FuzzyParameter" asp-action="Index"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Fuzzy Parameters</a></h5>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="FuzzySuitabilityInterval" asp-action="Index"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> Fuzzy Suitability Interval</a></h5>
                    </li>
                    <li class="list-group-item">
                        <h5><a asp-area="" asp-controller="UserAccount" asp-action="Index"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> User Accounts</a></h5>
                        <br />
                    </li>
                </ul>
            </div>
            <div class="col-sm-9">
                @RenderBody()
            </div>

        </div>
        <hr />
        <footer>
            <p>&copy; 2017 - RPDSS</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

<style>
    h5 {
        margin-top: 0px;
        margin-bottom: 0px;
    }

    .glyphicon {
        margin-right: 5px;
    }

    hr {
        margin:0px;
    }
</style>

RPDSS/Views/Shared/_LayoutFrontEnd.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" shrink-to-fit="no" />
    <meta http-equiv="X-UA-Compatible" content="IE-edge" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@{ViewData["Title"] = "_LayoutFrontEnd";} </title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="FrontEnd" asp-action="Index" class="navbar-brand">RPDSS</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="" asp-action="Index">Historical Data</a></li>
                    <li><a asp-area="" asp-controller="" asp-action="Index">Projected Suitable Rice Growth</a></li>
                    <li><a asp-area="" asp-controller="" asp-action="Index">Crop Calendar</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="text-center">
        <h1>
            <a href="~/images/crop-calendar-growth-tpr.jpg">
                <img src="~/images/crop-calendar-growth-tpr.jpg" alt="calendar" style="width:75%">
            </a>
        </h1>
     </div>

</body>
</html>



<div>
    @RenderBody()
    @RenderSection("Scripts", required:false)
</div>