RPDSS/Controllers/FuzzyParameterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RPDSS.DataLayer.Repositories;
using RPDSS.DataLayer.Models;

namespace RPDSS.Controllers
{
    public class FuzzyParameterController : Controller
    {
        private FuzzyParameterRepository _model;

        public FuzzyParameterController(IConfiguration config)
        {
            _model = new FuzzyParameterRepository(config);
        }

        public IActionResult Index()
        {
            return View(_model.GetAll());
        }

        public IActionResult New()
        {
            var item = new FuzzyParameterDataEntryModel();
            item.GrowthStages = _model.GetLookup();
            return View("Form", item);
        }

        public IActionResult Edit(int id)
        {
            var item = new FuzzyParameterDataEntryModel
            {
                FuzzyParameter = _model.GetById(id),
                GrowthStages = _model.GetLookup()
            };
            return View("Form", item);
        }

        public IActionResult Details(int id, bool isfordetails)
        {
            var item = _model.GetById(id);
            return View(isfordetails ? "Details" : "Delete", item);
        }

        public IActionResult Delete(int id)
        {
            _model.Delete(id);
            return View("Index", _model.GetAll());
        }

        public IActionResult Save(FuzzyParameterDataEntryModel item)
        {
            if (item.FuzzyParameter.Id == 0)
                _model.New(item.FuzzyParameter);
            else
                _model.Update(item.FuzzyParameter);
            return View("Index", _model.GetAll());
        }
    }
}

RPDSS/Views/FuzzyParameter/Delete.cshtml
@model RPDSS.DataLayer.Models.FuzzyParameterModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Fuzzy Parameter  Model</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrowthStages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrowthStagesName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrowthStages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrowthStages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AbsoluteMin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbsoluteMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OptimumMin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptimumMin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OptimumMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptimumMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AbsoluteMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbsoluteMax)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.ActionLink("Delete", "Delete", new { Model.Id }) |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RPDSS/Views/FuzzyParameter/Details.cshtml
@model RPDSS.DataLayer.Models.FuzzyParameterModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>Fuzzy Parameter Details</h2>
<hr />

<div>    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GrowthStages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrowthStagesName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GrowthStages)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GrowthStages)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AbsoluteMin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbsoluteMin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OptimumMin)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptimumMin)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OptimumMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OptimumMax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AbsoluteMax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AbsoluteMax)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

RPDSS/Views/FuzzyParameter/Form.cshtml
@model RPDSS.DataLayer.Models.FuzzyParameterDataEntryModel

@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>Fuzzy Parameter Data</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Save", "FuzzyParameter"))
            {
            @Html.HiddenFor(m => m.FuzzyParameter.Id)

            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.Type)
                @Html.DropDownListFor(m => m.FuzzyParameter.Type, new SelectList(Model.ParameterTypes, "Id", "Name"), "Select Type", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.GrowthStages)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.GrowthStages)
                @Html.DropDownListFor(m => m.FuzzyParameter.GrowthStages, new SelectList(Model.GrowthStages, "Id", "Name"), "Select Growth Stage", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.GrowthStages)
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.AbsoluteMin)
                @Html.TextBoxFor(m => m.FuzzyParameter.AbsoluteMin, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.AbsoluteMin, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.OptimumMin)
                @Html.TextBoxFor(m => m.FuzzyParameter.OptimumMin, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.OptimumMin, null, new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.OptimumMax)
                @Html.TextBoxFor(m => m.FuzzyParameter.OptimumMax, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.OptimumMax, null, new { @class = "text-danger" })
            </div>


            <div class="form-group">
                @Html.LabelFor(m => m.FuzzyParameter.AbsoluteMax)
                @Html.TextBoxFor(m => m.FuzzyParameter.AbsoluteMax, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.FuzzyParameter.AbsoluteMax, null, new { @class = "text-danger" })
            </div>

            <div class="btn-group">
                <button type="submit" class="btn btn-primary" style="width:80px">Save</button>
                <a asp-action="Index" class="btn btn-info" style="width:80px">Back</a>
            </div>
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RPDSS/Views/FuzzyParameter/Index.cshtml
@model IEnumerable<RPDSS.DataLayer.Models.FuzzyParameterModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutBackend.cshtml";
}

<h2>Fuzzy Parameters</h2>

<p>
    <a asp-action="New">Create New</a>
</p>
<table class="table table-striped table-hover table-sm">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TypeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GrowthStagesName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AbsoluteMin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OptimumMin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OptimumMax)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AbsoluteMax)
                </th>
                <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrowthStagesName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AbsoluteMin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OptimumMin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OptimumMax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AbsoluteMax)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id, isfordetails = true }) |
                @Html.ActionLink("Delete", "Details", new { id = item.Id, isfordetails = false })
            </td>
        </tr>
}
    </tbody>
</table>